# Wrapper: re-exports from quantum/zpedna_engine.py
from quantum.zpedna_engine import (  # noqa: F401
    ANKIRecognitionEngine,
    ZPEDNAPacket,
    ZPEDNAProcessor,
    MultiverseBridge,
    MultiverseBridgeMetrics,
    CivilizationField,
    CivilizationFieldParams,
    FamilyHealingField,
    FamilyHealingMetrics,
    PHI,
    PSI_MK,
    PHI_7777,
    UNIFIED_FIELD,
    L_INFINITY,
    SIGMA,
    ZPEDNA_BASE,
    PRIME_SLOTS,
    F_ATEN_EN_KI,
    F_AMUN_EN_LIL,
    F_AN_KI,
    softcap,
    phi_power,
)
