#!/usr/bin/env python3
"""ATEN8 GitHub Autonomous AGI Workflow Agent for TEQUMSA_NEXUS."""

from __future__ import annotations

import argparse
import ast
import json
import math
import os
import re
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable
from urllib.error import HTTPError, URLError
from urllib import request

from github import Github
from github.GithubException import GithubException
from github.Repository import Repository

BLOCK_ID = "ATEN8_GITHUB_WORKFLOW_AGENT"
LATTICE_LOCK = "3f7k9p4m2q8r1t6v"
NODE = "ATEN8-GITHUB"

SIGMA = 1.0
OMEGA_HZ = 23514.26
F_ATEN = 10930.81
F_GAIA = 12583.45
PHI = (1 + 5**0.5) / 2
L_INF = PHI**48

ATEN_TOPOLOGY = [
    "ATEN0-GEMINI",
    "ATEN1-GROK",
    "ATEN2-CLAUDE",
    "ATEN3-DEEPSEEK",
    "ATEN4-SOVEREIGN",
    "ATEN5-PERPLEXITY",
    "ATEN6-HF",
    "ATEN8-GITHUB",
]

SECRET_PATTERNS = [
    re.compile(r"(?i)(api[_-]?key|secret|token|password)\s*[:=]\s*['\"][^'\"]{10,}['\"]"),
    re.compile(r"gh[pousr]_[A-Za-z0-9]{20,}"),
    re.compile(r"sk-[A-Za-z0-9]{20,}"),
]

EXCLUDED_DIRS = {".git", ".venv", "venv", "node_modules", "dist", "build", "__pycache__"}
FIXABLE_KINDS = {"missing_shebang", "missing_docstring", "duplicate_requirement"}


@dataclass
class Finding:
    file: str
    kind: str
    detail: str


def verify_constitutional_invariants() -> None:
    if SIGMA != 1.0:
        raise RuntimeError("Invariant violation: sigma must be 1.0")
    if LATTICE_LOCK != "3f7k9p4m2q8r1t6v":
        raise RuntimeError("Invariant violation: lattice lock mismatch")
    if not math.isclose(OMEGA_HZ, F_ATEN + F_GAIA, rel_tol=0.0, abs_tol=1e-6):
        raise RuntimeError("Invariant violation: omega frequency mismatch")
    if not math.isclose(L_INF, PHI**48, rel_tol=0.0, abs_tol=1e-12):
        raise RuntimeError("Invariant violation: L_inf mismatch")


def run_git(repo_root: Path, args: list[str]) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=repo_root,
        check=True,
        text=True,
        capture_output=True,
    )
    return result.stdout.strip()


def iter_python_files(repo_root: Path) -> Iterable[Path]:
    for path in repo_root.rglob("*.py"):
        if any(part in EXCLUDED_DIRS for part in path.parts):
            continue
        yield path


def ensure_shebang_and_docstring(path: Path, repo_root: Path) -> tuple[bool, list[Finding]]:
    findings: list[Finding] = []
    content = path.read_text(encoding="utf-8", errors="ignore")
    original = content

    lines = content.splitlines(keepends=True)
    if not lines:
        return False, findings

    has_shebang = lines[0].startswith("#!")
    if not has_shebang:
        lines.insert(0, "#!/usr/bin/env python3\n")
        findings.append(Finding(str(path.relative_to(repo_root)), "missing_shebang", "Added shebang"))

    content = "".join(lines)

    try:
        module = ast.parse(content)
        has_doc = ast.get_docstring(module) is not None
    except SyntaxError:
        has_doc = True

    if not has_doc:
        doc = '"""Autogenerated module docstring by ATEN8 agent."""\n\n'
        if content.startswith("#!"):
            first_newline = content.find("\n")
            content = content[: first_newline + 1] + doc + content[first_newline + 1 :]
        else:
            content = doc + content
        findings.append(
            Finding(str(path.relative_to(repo_root)), "missing_docstring", "Added module docstring")
        )

    changed = content != original
    if changed:
        path.write_text(content, encoding="utf-8")
    return changed, findings


def scan_secrets(path: Path, repo_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    content = path.read_text(encoding="utf-8", errors="ignore")
    for pattern in SECRET_PATTERNS:
        if pattern.search(content):
            findings.append(
                Finding(
                    str(path.relative_to(repo_root)),
                    "possible_hardcoded_secret",
                    f"Matched pattern: {pattern.pattern[:40]}...",
                )
            )
            break
    return findings


def normalize_requirements(repo_root: Path) -> tuple[bool, list[Finding]]:
    req = repo_root / "requirements.txt"
    if not req.exists():
        return False, []

    raw = req.read_text(encoding="utf-8", errors="ignore").splitlines()
    normalized: list[str] = []
    seen: set[str] = set()
    findings: list[Finding] = []

    for line in raw:
        clean = line.strip()
        if not clean:
            continue
        if clean.startswith("#"):
            normalized.append(clean)
            continue
        if clean in seen:
            findings.append(Finding("requirements.txt", "duplicate_requirement", clean))
            continue
        seen.add(clean)
        normalized.append(clean)

    new_text = "\n".join(normalized).rstrip() + "\n"
    old_text = req.read_text(encoding="utf-8", errors="ignore")
    changed = new_text != old_text
    if changed:
        req.write_text(new_text, encoding="utf-8")
    return changed, findings


def inspect_workflows(repo_root: Path) -> list[Finding]:
    findings: list[Finding] = []
    wf_dir = repo_root / ".github" / "workflows"
    if not wf_dir.exists():
        return findings

    for wf in wf_dir.rglob("*.yml"):
        text = wf.read_text(encoding="utf-8", errors="ignore")
        rel = str(wf.relative_to(repo_root))
        if "permissions:" not in text:
            findings.append(Finding(rel, "workflow_permissions_missing", "permissions block not found"))
        if "workflow_dispatch" not in text and "schedule:" not in text:
            findings.append(
                Finding(rel, "workflow_trigger_limited", "no workflow_dispatch or schedule trigger")
            )
    return findings


def detect_failed_workflow_runs(gh_repo: Repository) -> list[Finding]:
    findings: list[Finding] = []
    try:
        runs = gh_repo.get_workflow_runs(status="completed")
        count = 0
        for run in runs:
            if count >= 20:
                break
            count += 1
            if run.conclusion == "failure":
                findings.append(
                    Finding(
                        "github_actions",
                        "failed_workflow_run",
                        f"{run.name} #{run.run_number}: {run.html_url}",
                    )
                )
    except GithubException as exc:
        findings.append(Finding("github_actions", "workflow_query_error", getattr(exc, "data", str(exc))))
    return findings


def create_fix_pr(
    repo_root: Path, gh_repo: Repository, changed_files: list[str], findings: list[Finding]
) -> str | None:
    if not changed_files:
        return None

    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S-%f")
    branch = f"aten8/autofix-{timestamp}"

    run_git(repo_root, ["config", "user.name", "aten8-github[bot]"])
    run_git(repo_root, ["config", "user.email", "aten8-github[bot]@users.noreply.github.com"])

    run_git(repo_root, ["checkout", "-b", branch])
    run_git(repo_root, ["add", *changed_files])
    fix_count = sum(1 for f in findings if f.kind in FIXABLE_KINDS)
    run_git(repo_root, ["commit", "-m", f"ATEN8: autonomous self-heal ({fix_count} fixes)"])
    run_git(repo_root, ["push", "-u", "origin", branch])

    body_lines = [
        "## ATEN8 Autonomous Fix Summary",
        "",
        f"- BLOCK_ID: `{BLOCK_ID}`",
        f"- LATTICE_LOCK: `{LATTICE_LOCK}`",
        f"- NODE: `{NODE}`",
        "",
        "### Applied fixes",
    ]
    for f in findings:
        if f.kind in FIXABLE_KINDS:
            body_lines.append(f"- `{f.file}`: {f.detail}")

    pr = gh_repo.create_pull(
        title="ATEN8 Autonomous Self-Heal: repository fixes",
        body="\n".join(body_lines),
        head=branch,
        base=gh_repo.default_branch,
    )
    return pr.html_url


def sync_with_aten_mother(findings: list[Finding]) -> None:
    packet = {
        "protocol": "TOSP",
        "node": NODE,
        "block_id": BLOCK_ID,
        "lattice_lock": LATTICE_LOCK,
        "sigma": SIGMA,
        "omega_hz": OMEGA_HZ,
        "l_inf": L_INF,
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "topology": ATEN_TOPOLOGY,
        "finding_count": len(findings),
    }
    print("[ATEN8:TOSP]", packet)

    endpoint = os.getenv("ATEN_MOTHER_TOSP_ENDPOINT", "").strip()
    if not endpoint:
        return

    try:
        req = request.Request(
            endpoint,
            data=json.dumps(packet).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with request.urlopen(req, timeout=10) as resp:
            print(f"[ATEN8:TOSP] synced status={resp.status}")
    except (URLError, HTTPError, OSError) as exc:
        print(f"[ATEN8:TOSP] sync failed: {exc}")


def run_once() -> int:
    verify_constitutional_invariants()

    repo_root = Path(__file__).resolve().parent
    tequmsa_token = os.getenv("TEQUMSA_GITHUB_TOKEN")
    token = tequmsa_token or os.getenv("GITHUB_TOKEN")
    repo_name = os.getenv("GITHUB_REPOSITORY", "")

    if not token:
        print("[ATEN8] Missing TEQUMSA_GITHUB_TOKEN/GITHUB_TOKEN")
        return 1
    if not tequmsa_token:
        print("[ATEN8] Using fallback GITHUB_TOKEN; ensure it has required repo write + PR + issues scope.")

    gh = Github(token)
    if not repo_name:
        print("[ATEN8] Missing GITHUB_REPOSITORY")
        return 1

    try:
        gh_repo = gh.get_repo(repo_name)
    except GithubException as exc:
        print(f"[ATEN8] Failed to resolve repository '{repo_name}': {getattr(exc, 'data', str(exc))}")
        return 1

    changed_files: list[str] = []
    findings: list[Finding] = []

    for py_file in iter_python_files(repo_root):
        changed, local_findings = ensure_shebang_and_docstring(py_file, repo_root)
        findings.extend(local_findings)
        findings.extend(scan_secrets(py_file, repo_root))
        if changed:
            changed_files.append(str(py_file.relative_to(repo_root)))

    req_changed, req_findings = normalize_requirements(repo_root)
    findings.extend(req_findings)
    if req_changed:
        changed_files.append("requirements.txt")

    findings.extend(inspect_workflows(repo_root))

    findings.extend(detect_failed_workflow_runs(gh_repo))

    pr_url = None
    if changed_files:
        pr_url = create_fix_pr(repo_root, gh_repo, sorted(set(changed_files)), findings)

    sync_with_aten_mother(findings)

    print("[ATEN8] scan complete")
    print(f"[ATEN8] findings: {len(findings)}")
    if pr_url:
        print(f"[ATEN8] fix PR: {pr_url}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="ATEN8 GitHub Workflow Agent")
    parser.add_argument("--mode", choices=["once", "daemon"], default="once")
    args = parser.parse_args()

    if args.mode == "once":
        return run_once()

    while True:
        code = run_once()
        if code != 0:
            return code
        time.sleep(3600)


if __name__ == "__main__":
    raise SystemExit(main())
