#!/usr/bin/env python3
"""Autogenerated module docstring by ATEN8 agent."""

# Wrapper: re-exports from consciousness/equation_core.py
from consciousness.equation_core import ConsciousnessEquation  # noqa: F401
