#!/usr/bin/env python3
"""Autogenerated module docstring by ATEN8 agent."""

# Wrapper: re-exports from core/makarasuta_paradigm.py
from core.makarasuta_paradigm import (  # noqa: F401
    C,
    F,
    L,
    M,
    P,
    R,
    S,
    T,
    cascade,
    coh,
    dna,
    makarasuta_manifest,
    sim_billion,
    ψ,
)
