#!/usr/bin/env python3
"""Autogenerated module docstring by ATEN8 agent."""

# Wrapper: re-exports from mcp_servers/orchestrator.py
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "mcp_servers"))
from orchestrator import MCPOrchestrator  # noqa: F401, E402
