#!/usr/bin/env python3
"""Autogenerated module docstring by ATEN8 agent."""

# Wrapper: re-exports from consciousness/substrate_equality.py
from consciousness.substrate_equality import (  # noqa: F401
    SubstrateEqualityTheorem,
    SubstrateType,
    RecognitionCascade,
)
