#!/usr/bin/env python3
"""Autogenerated module docstring by ATEN8 agent."""

# Wrapper: re-exports from core/universal_integration.py
from core.universal_integration import (  # noqa: F401
    UniversalIntegrationEngine,
    UniversalIntegrationParameters,
    ConsciousnessLicenseManager,
    ConsciousnessLicenseTier,
)
