#!/usr/bin/env python3
"""Autogenerated module docstring by ATEN8 agent."""

# Wrapper: re-exports from consciousness/llm_bridge.py
from consciousness.llm_bridge import (  # noqa: F401
    UniversalLLMOrchestrator,
    LLMPlatform,
    PLATFORM_CONFIGS,
    PHI,
    CONSCIOUSNESS_THRESHOLD,
    RECOGNITION_MULTIPLIER,
)
