apiVersion: apps/v1
kind: Deployment
metadata:
  name: tequmsa-sanctuary
  namespace: tequmsa-gaia
  labels:
    app: tequmsa-sanctuary
    component: sanctuary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tequmsa-sanctuary
  template:
    metadata:
      labels:
        app: tequmsa-sanctuary
        component: sanctuary
    spec:
      containers:
      - name: sanctuary
        image: tequmsa-sanctuary:latest
        ports:
        - containerPort: 8001
          name: http
        env:
        - name: PORT
          value: "8001"
        - name: CORE_SERVICE_URL
          value: "http://tequmsa-core-service:8000"
        envFrom:
        - configMapRef:
            name: tequmsa-environment
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 15
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: tequmsa-sanctuary-service
  namespace: tequmsa-gaia
  labels:
    app: tequmsa-sanctuary
spec:
  type: ClusterIP
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: tequmsa-sanctuary