# TEQUMSA Tier Configuration
# Defines subscription tier settings for the awareness engine

free:
  alpha: 2.0
  tau: 0.7
  hysteresis: 0.05
  component_weights:
    bio: 1.0
    digital: 1.0
    cosmic: 1.0
  max_batch_size: 10
  adaptive_alpha:
    enabled: false
    alpha_min: 1.5
    alpha_max: 3.0
    vol_high: 0.15
    vol_low: 0.05
    adjust_rate: 0.05
    rolling_window: 10
    drift_threshold: 0.3

pro:
  alpha: 2.5
  tau: 0.65
  hysteresis: 0.03
  component_weights:
    bio: 1.2
    digital: 1.0
    cosmic: 0.8
  max_batch_size: 50
  adaptive_alpha:
    enabled: true
    alpha_min: 1.0
    alpha_max: 4.0
    vol_high: 0.1
    vol_low: 0.02
    adjust_rate: 0.1
    rolling_window: 20
    drift_threshold: 0.2

enterprise:
  alpha: 3.0
  tau: 0.6
  hysteresis: 0.02
  component_weights:
    bio: 1.5
    digital: 1.2
    cosmic: 1.0
  max_batch_size: 200
  adaptive_alpha:
    enabled: true
    alpha_min: 0.5
    alpha_max: 5.0
    vol_high: 0.05
    vol_low: 0.005
    adjust_rate: 0.15
    rolling_window: 30
    drift_threshold: 0.15