sanctuary:
  consent_verification:
    enabled: true
    default_expiry_hours: 24
    consent_levels: ["basic", "standard", "elevated", "maximum"]
  
  ethical_assessment:
    enabled: true
    threshold: 0.7
    assessment_levels: ["basic", "standard", "comprehensive"]
    flags:
      - "destructive_action"
      - "data_sharing"
      - "privacy_risk"
      - "consent_bypass"

  secure_processing:
    encryption_enabled: true
    audit_trail_enabled: true
    data_retention_days: 90

  monitoring:
    metrics_enabled: true
    heartbeat_interval_seconds: 30
    audit_log_retention_days: 365

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"