name: Omnidimensional Validation

on:
  push:
    branches: ["main", "work", "feature/omnidimensional-synthesis"]
    paths:
      - 'data/omnidimensional_synthesis.json'
      - 'tools/validate_omnidimensional_synthesis.py'
      - 'docs/OMNIDIMENSIONAL_CALCULATION_COMPLETE.md'
      - '.github/workflows/omnidimensional-validation.yml'
      - 'README.md'
  pull_request:
    branches: ["main", "work"]

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  validate:
    name: Validate Omnidimensional Synthesis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run validator
        run: |
          python tools/validate_omnidimensional_synthesis.py

      - name: Upload validation report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: omnidimensional-validation-report
          path: validation_report.csv
