name: Omnidimensional Validation

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run validator
        run: |
          python tools/validate_omnidimensional_synthesis.py
      - name: Upload validation report
        uses: actions/upload-artifact@v4
        with:
          name: validation_report
          path: validation_report.csv
